### ISSUE TITLE
No telemetry decoding

### ISSUE THREAD

**Issue by Alienix33** [brinuk/Antenna-Tracker-for-FRsky-Telemetry#1]
I am trying to use your librairy

My configuration :
- Matek FC connected to X8R receiver via SBus and Fport
- Radiomaster TX16S running Yapuu telemetry
every thing work nicely and telemetry also.
Now I when I connect Ardino (uno or mega) running Sportdecodertracker to UART of TX16S ( configured as " telemetry mirror") with or without signal inverter all datas displayed by Arduino remain at 0 including GPS (which is received and displayed on Yapuu widget).
When I spy this UART output ( with FDTI and realterm) there is a flow of data at 57600 bauds that I cannot decode .
What is wrong ? do you have any suggestion ?

**Comment by brinuk** [comment]
Thank you for your email. 
If you view the Realterm output as Hex you should see frames starting with 0x7E the next byte 0x83(a GPS frame) then 2 bytes 0x0800 (latitude and longitude frame). Until you can see these with Realterm you will not get the tracker to decode the data stream.
Once you can see the above data frames then run the SportDecoder sketch on the Arduino Uno. This is the simplest of the sketches. 
I picked the telemetry up from the Sport pin of the FrSky R9M module as you know.
I hope that this helps.

**Comment by brinuk** [comment]
There are two functions in the library that I used for testing the incoming data, these may be of assistance to you.
The library reads the incoming data into a 2D array called hexData[frame][cell].

In an Arduino Uno sketch
1 - Declare object FrSkyR9MSportDecoder decode
2 - Start things going with decode.beginTest().
3 - The incoming data is read and the array is filled by function decode.plainReadData().
4 - The contents of this array may be printed as data frames by running function decode.printHexData().
Also the raw incoming data from Realterm can be read and printed as frames by running decode.readRealTerm().
(You should see, among others, a GPS lat/long frame starting 0x70,0x83,0x00,0x80, etc)
These may be of assistance to you in debugging your problem.
(readRealTerm() is shown in FrSkyR9MSportDecoder.h as a Private function you might have to move this to Public in your copy of the library)

**Comment by Alienix33** [comment]
Thanks  i will try


Le dim. 28 nov. 2021 à 13:48, Brian Lambert ***@***.***> a
écrit :

**Comment by Alienix33** [comment]
Hi,
I checked the UART output of my TX16S radio with Realterm the result is:
- with or without an inverter there is a data flow but it is not compliant with FrSky telemetry protocol.
Conclusion even if my radio receive an SPORT telemetry from X8R receiver, the OPEN TX function called "telemetry mirror " to configure the UART is not really a mirror and seem to provide data under another protocol that I cannot decode.
So the issue is on my side  and I close this .
